name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/zxczoxc125/dev-tips/compare/$PREVIOUS_TAG...$RESOLVED_VERSION