name: test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choice Environment to Deploy
        required: true
        default: 'prod'
        options:
          - 'prod'
          - 'staging'

env:
  ENV_NAME: ${{ github.event.inputs.environment }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ env.ENV_NAME }}
      url: https://${{ env.ENV_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo ${{ env.ENV_NAME }}
