name: test

on:
  workflow_dispatch:

jobs:
  deployment:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo 1
  add-git-tag:
    runs-on: ubuntu-latest
    needs: deployment
    if: success()
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        run: echo 2
  add-git-tag2:
    runs-on: ubuntu-latest
    needs: add-git-tag
    if: success()
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        run: echo 3