name: test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choice Environment to Deploy
        required: true
        default: 'prod'
        options:
          - 'prod'
          - 'staging'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: staging
        run: echo ${{ inputs.environment }}
