name: test

on:
  workflow_dispatch:

env:
  ENV_NAME: ${{ github.event.inputs.environment }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0
      - name: test
        run: npm start
      - name: Short Sha
        id: short_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: test2
        run: git branch -r --contains ${{ steps.short_sha.outputs.sha_short }}
