name: test

on:
  workflow_dispatch:

jobs:
  connect-open-vpn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Open VPN
        run: echo ${{ github.ref_name }}
