name: test

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: staging
        uses: ./.github/actions/e2e
        with:
          env-name: staging
      - name: prod
        uses: ./.github/actions/e2e
        with:
          env-name: prod
