name: test

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choice Environment to Deploy
        required: true
        default: "staging"
        options:
          - "staging"
          - "opt"
          - "test"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: npm ${{ github.event.inputs.environment || 'staging' }}
