name: Deployment to Production

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        # with:
        #   publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}