name: test

on:
  workflow_dispatch:

env:
  ENV_NAME: ${{ github.event.inputs.environment }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: npm start
