name: test

on:
  workflow_dispatch:
    inputs:
      VERSION:
        type: choice
        description: Choice Version to Deploy
        required: true
        default: 'patch'
        options:
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  add-git-tag:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.PAT }}
          default_bump: ${{ github.event.inputs.VERSION }}
          tag_prefix: ''
          append_to_pre_release_tag: 'asdasdsadsa'
      - name: check new tag
        run: |
          echo ${{ steps.tag_version.outputs.new_tag }}
      - name: Slack Notification
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: test
          SLACK_COLOR: success
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Git tag가 정상적으로 추가되었습니다. Version: ${{ steps.tag_version.outputs.new_tag }}'
          SLACK_TITLE: Force Pipeline Alert
          SLACK_USERNAME: pipeline alert service
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
  generate-release-note:
    needs: add-git-tag
    if: success()
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          # github-action-get-previous-tag 액션이 올바르게 동작하기 위해서
          fetch-depth: 0
      - name: Get current new tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          fallback: 1.0.0
      - name: Check tag
        run: |
          echo ${{ steps.previoustag.outputs.tag }}
      - uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.previoustag.outputs.tag }}
          # 깃헙 release note는 draft -> publish 과정을 거침
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
