name: test

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Ref brach name
        run: |
          echo "${{ github.actor }}"
