name: test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choice Environment to Deploy
        required: true
        default: 'prod'
        options:
          - 'prod'
          - 'staging'

env:
  ENV_NAME: ${{ github.event.inputs.environment }}

jobs:
  caption: ${{ github.event.inputs.environment }}
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
      url: https://${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo ${{ env.ENV_NAME }}
