name: test

on:
  workflow_dispatch:

jobs:
  add-git-tag:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.PAT }}
          # default_bump: ${{ github.event.inputs.VERSION }}
          tag_prefix: ''
      - name: check new tag
        run: |
          echo ${{ steps.tag_version.outputs.new_tag }}