name: test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: a
        run: |
          node -e 'throw Error('1233');'
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: b
        run: |
          echo "22"
  job3:
    needs: [job1, job2]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: c
        run: | 
          echo ${{ !contains(needs.*.result, 'failure') ? 'success' : 'failure' }}
