name: Deployment to Production

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
      - uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.previoustag.outputs.tag }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}